// <auto-generated />
using System;
using EconomicDataTracker.Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EconomicDataTracker.Migrations.ApplicationContext
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241111222634_UpdateFredSeriesAllCommoditities")]
    partial class UpdateFredSeriesAllCommoditities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EconomicDataTracker.Entities.Models.FredObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FredSeriesId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("FredSeriesId");

                    b.ToTable("FredObservations");
                });

            modelBuilder.Entity("EconomicDataTracker.Entities.Models.FredObservationUpdateTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FredSeriesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FredSeriesId");

                    b.ToTable("FredObservationUpdateTrackers");
                });

            modelBuilder.Entity("EconomicDataTracker.Entities.Models.FredSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FredSeries");
                });

            modelBuilder.Entity("EconomicDataTracker.Entities.Models.FredObservation", b =>
                {
                    b.HasOne("EconomicDataTracker.Entities.Models.FredSeries", "FredSeries")
                        .WithMany("Observations")
                        .HasForeignKey("FredSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FredSeries");
                });

            modelBuilder.Entity("EconomicDataTracker.Entities.Models.FredObservationUpdateTracker", b =>
                {
                    b.HasOne("EconomicDataTracker.Entities.Models.FredSeries", "FredSeries")
                        .WithMany()
                        .HasForeignKey("FredSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FredSeries");
                });

            modelBuilder.Entity("EconomicDataTracker.Entities.Models.FredSeries", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
